// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mySampleApp1.weatherForecast.Infra;

#nullable disable

namespace mySampleApp1.weatherForecast.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mySampleApp1.weatherForecast.Domain.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("Date");

                    b.Property<string>("Summary")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Summary");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer")
                        .HasColumnName("TemperatureC");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 10, 4),
                            Summary = "Sweltering",
                            TemperatureC = 35
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 10, 5),
                            Summary = "Cool",
                            TemperatureC = 37
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2024, 10, 6),
                            Summary = "Chilly",
                            TemperatureC = 9
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2024, 10, 7),
                            Summary = "Freezing",
                            TemperatureC = -9
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2024, 10, 8),
                            Summary = "Warm",
                            TemperatureC = 51
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
